### PR TITLE
charToFact

### PR DESCRIPTION
**Pull request by 2005m**

### CODE REVIEW

**Comment by 2005m** [comment]
@SebKrantz, just fyi, you might be interested by function `kit::charToFact`. It is quite fast.

**Comment by SebKrantz** [comment]
Hi, thanks a lot. I‘d actually be grateful if you want to start
contributing to collapse. I’m very interested in your hashing algorithm and
would like to adopt it for unordered grouping in GRP() and functions like
qF, funique, fNdistinct, fmode etc. I need to find time for that though and
that is a bit limited at the moment. Especially faster grouping performance
would be amazing as collapse is already competitive with data.table and
supports all the statistical computations.

Best regards,

Sebastian

**Comment by 2005m** [comment]
Hi, thank you for your message. If you are interested in using an efficient and fast hashing algorithm, I would recommend you to have a look at https://github.com/Cyan4973/xxHash . It is used in the `fst` package. You should be able to achieve really astonishing performance with it. My hash algorithm is just implemented in an efficient way but there is nothing actually specifial about it.  I am sure you can achieve much better performance than I did ;-) .
Given that you are using the same GPL license as I do (which is compatible with base R) then you can use the code of my package in your package (following the license rules) without directly depending on my package. I do expose a lot of C functions in my package so others can use them directly at C level in their own package. I can expose more functions if you are interested in this approach.  This describe in the R extension manual 5.4.3 Linking to native routines in other packages.
Faster unordered grouping is definitely possible but I am not really looking at it for now, I prefer to code basic functions for now.
Regarding contributions, I'll be honest, I don't have much time for it and when I do I stopped doing it because I lose control over what I write and how the code evolve and when it is integrated. I had this unpleasant experience when I contributed `fifelse` and `fcase` to `data.table`. I have much more freedom maintaining my own package.

**Comment by SebKrantz** [comment]
Hi, thanks a lot for your reply and the suggestions. I‘ll look into xxHash
and also the options for using some of your code, and I‘ll get back to you
if I do use your code to discuss it. Also fully understand your stance on
contributing, although collapse is at an early stage of development and
really only authored by myself, so you‘d have a lot of freedom and high
impact potential. I‘ll also create the ‚fastverse‘ at some point not too
far away.

**Pull request merged**
